### ISSUE TITLE
Zalgo not working

### ISSUE THREAD

**Issue by xDp64xG** [planetarian/BetterDiscordPlugins#2]
So I've been attempting to try out the new plugin Zalgo, and read how to use it, and does not seem to be working at all. I have restarted discord for the plugin to properly load but is not working. I am using Zere's Fork if that means anything.

**Comment by planetarian** [comment]
there currently seems to be an issue where the load event of zere's library frequently doesn't fire when you start or reload the client, causing plugins that use it to fail to run their initialization code. I asked him about this the other day and he said he was working on reworking his library to prevent this from happening in the first place, but until he finishes and publishes that work, when this happens the only solution seems to be to turn the plugin off and back on, or try reloading again.

I may implement a timer-based solution that automatically runs the initialization after a set time, whether zere's lib is ready or not, but this may still cause the plugin to fail outright if ZeresLib itself failed to load for some reason.

This issue also affects my other plugins that rely on ZeresLib.

**Comment by planetarian** [comment]
I added a timer-based fallback so that the initialization code will be called one way or another whether the load event fires or not. So far it seems to be working, and I haven't received any further complaints about this problem. If the issue recurs, we can reopen this, but I'm calling this one worked-around for the moment.
