### ISSUE TITLE
Zalgo is broken

### ISSUE THREAD

**Issue by bur19149** [planetarian/BetterDiscordPlugins#9]
Either im doing something really wrong or its broken XD 
![image](https://user-images.githubusercontent.com/56315119/70954705-9403f480-206e-11ea-9b65-ba9714dd687a.png)

**Comment by planetarian** [comment]
discord updated their inputbox code *again*, and this time it's a doozy. instead of using an input/textarea like before, they use a whacky editable-div system, with each line or bit of formatted text being split into nested divs ... it's likely going to be a bit of a pain to fix. I'll be looking into it soon.

**Comment by mrx12335** [comment]
ok thanks for the update
 ̶a̶c̶c̶i̶d̶e̶n̶t̶l̶y̶ ̶u̶s̶e̶d̶ ̶a̶ ̶f̶r̶i̶e̶n̶d̶s̶ ̶a̶c̶c̶o̶u̶n̶t̶

**Comment by planetarian** [comment]
this has been fixed in 0.4.0. sorry it took so long; been getting fed up with discord's shit tbh.
